controllers/dish_blueprint.py
from flask import Blueprint, redirect, url_for
from resources.restaurant import RestaurantByID
from resources.dish import DishByID


dish_blueprint = Blueprint('dish', __name__)


@dish_blueprint.route('/delete/<string:dish_id>', methods=['GET'])
def delete_dish(dish_id):
    dish, dish_status_code = DishByID.get(dish_id)
    restaurant, restaurant_status_code = RestaurantByID.get(dish['restaurant_id'])
    DishByID.delete(dish_id)
    return redirect(url_for("restaurant.restaurant_by_name", name=restaurant['name']))

controllers/restaurants_blueprint.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from resources.restaurant import Restaurant, RestaurantList, RestaurantListByUser, RestaurantByID, RestaurantGetRandom,\
    RestaurantByUser
from resources.dish import DishByRestaurantID, DishListByRestaurantID
from common.decorators import requires_login, requires_admin

restaurants_blueprint = Blueprint('restaurants', __name__)
restaurant_blueprint = Blueprint('restaurant', __name__)

# RESTAURANTS ################


@restaurants_blueprint.route('/', methods=['GET'])
@requires_login
def restaurant_list():
    user = session.get('user_name')
    payload, status_code = RestaurantListByUser.get(user)
    if status_code == 200:
        return render_template('restaurant/index.html', restaurants=payload['restaurants'],
                               user_name=session['user_name'], restaurant=Restaurant)
    else:
        return render_template('error.html', error='Please Login.')

# RESTAURANT ################


@restaurant_blueprint.route('/random', methods=['GET'])
@requires_login
# @requires_admin
def get_random():
    payload, status_code = RestaurantGetRandom.get()
    if status_code == 200:
        return redirect(url_for(".restaurant_by_name", name=payload['name']))
    else:
        return render_template('error.html', error=payload['message'])


@restaurant_blueprint.route('/<string:name>', methods=['GET'])
@requires_login
def restaurant_by_name(name):
    if session.get('user_name'):
        payload, status_code = Restaurant.get(name)
        payload.update(DishListByRestaurantID.get(payload['id'])[0])
        if status_code == 200:
            return render_template('restaurant/restaurant.html', restaurant=payload)
        else:
            return render_template('error.html', error=payload['message'])
    else:
        return render_template('error.html', error='Please Login.')


@restaurant_blueprint.route('/new', methods=['POST', 'GET'])
@requires_login
def create_restaurant():
    if request.method == 'GET':
        return render_template('restaurant/new.html')
    else:
        payload, status_code = Restaurant.post(request.form['name'])
        if status_code == 201:
            return redirect(url_for("restaurants.restaurant_list"))
        else:
            return render_template('error.html', error=payload['message'])


@restaurant_blueprint.route('/edit/<string:restaurant_id>', methods=['POST', 'GET'])
@requires_login
def edit_restaurant(restaurant_id):
    payload, status_code = RestaurantByID.get(restaurant_id)
    if request.method == 'POST':
        Restaurant.put(payload['name'])
        return redirect(url_for("restaurants.restaurant_list"))
    else:
        return render_template("restaurant/edit.html", restaurant=payload)


@restaurant_blueprint.route('/remove/<string:restaurant_id>', methods=['GET'])
@requires_login
def remove_restaurant_from_list(restaurant_id):
    payload, status_code = RestaurantByUser.delete(session.get('user_name'), restaurant_id)
    if status_code == 200:
        return redirect(url_for("restaurants.restaurant_list"))
    else:
        return render_template('error.html', error=payload['message'])


@restaurant_blueprint.route('/delete/<string:restaurant_id>', methods=['GET'])
@requires_login
@requires_admin
def delete_restaurant(restaurant_id):
    restaurant, status_code_fetch = RestaurantByID.get(restaurant_id)
    payload, status_code = Restaurant.delete(restaurant['name'])
    if status_code == 200:
        return redirect(url_for("restaurants.restaurant_list"))
    else:
        return render_template('error.html', error=payload['message'])


@restaurant_blueprint.route('/<string:restaurant_id>/dish/new', methods=['POST', 'GET'])
@requires_login
def create_restaurant_dish(restaurant_id):
    if request.method == 'GET':
        return render_template('restaurant/dish/new.html', restaurant_id=restaurant_id)
    else:
        DishByRestaurantID.post(restaurant_id)
        payload, status_code = RestaurantByID.get(restaurant_id)
        return redirect(url_for(".restaurant_by_name", name=payload['name']))

templates/restaurant/edit.html
{%  extends "base.html" %}
{%  block content %}
    <div class="container auth-page-form" id="edit-restaurant-page-form">
        <h5>Edit Restaurant:</h5>
        <form id="edit-restaurant" action="{{url_for('restaurant.edit_restaurant', restaurant_id=restaurant.id)}}" method="POST">
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class='form-control' id="restaurant_name" name="name" value="{{ restaurant.name }}" disabled>
            </div>
            <div class="form-group">
                <label for="review">Review</label>
                <input type="text" class='form-control' id="restaurant_review" name="review" value="{{ restaurant.review }}">
            </div>
            <button type="submit" class="btn btn-outline-success btn-sm" id="edit-restaurant-button">Edit Restaurant</button>
        </form>
    </div>
{% endblock %}

templates/restaurant/index.html
{%  extends "base.html" %}
{%  block content %}
    <header>
    </header>
    <div class="container">
        <div class="col-sm">
            <h2>Hello, {{ user_name }}!</h2>
            <h2 class="mb-3">Restaurant List:</h2>
            <a class="btn btn-outline-success btn-sm mb-3" href="/restaurant/new">Add a Restaurant</a>
            <a class="btn btn-outline-secondary btn-sm mb-3" href="{{ url_for('restaurant.get_random') }}"> Choose a Random Restaurant</a>
            <ul class="list-group">
                {% for restaurant in restaurants %}
                    <div class="col-12">
                        <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center" href="/restaurant/{{ restaurant.name }}">
                            <h4>{{restaurant.name}}</h4>
                            <small class="badge badge-info badge-pill"> {{ restaurant.review }} stars</small>
                        </a>
                    </div>
                    <div class="col-6">
                        <a class="btn btn-secondary btn-sm" href="{{ url_for('restaurant.edit_restaurant', restaurant_id=restaurant.id) }}">
                            Edit
                        </a>
                        <a class="btn btn-outline-danger btn-sm" href="{{ url_for('restaurant.remove_restaurant_from_list', restaurant_id=restaurant.id) }}">
                            Remove from list
                        </a>
                        {% if session.get('user_name') == config.ADMIN %}
                        <a class="btn btn-outline-danger btn-sm" href="{{ url_for('restaurant.delete_restaurant', restaurant_id=restaurant.id) }}">
                            Permanently Delete
                        </a>
                        {% endif %}
                        <a class="btn btn-secondary btn-sm" href="{{ url_for('restaurant.create_restaurant_dish', restaurant_id=restaurant.id) }}">
                            Add Dish
                        </a>
                    </div>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

templates/restaurant/new.html
{%  extends "base.html" %}
{%  block content %}
    <div class="container auth-page-form" id="new-restaurant-page-form">
        <h5>Create new Restaurant:</h5>
        <form id="new-restaurant" action="{{url_for('restaurant.create_restaurant')}}" method="POST">
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class='form-control' id="restaurant_name" name="name">
            </div>
            <div class="form-group">
                <label for="review">Review</label>
                <input type="text" class='form-control' id="restaurant_review" name="review">
            </div>
            <button type="submit" class="btn btn-outline-success btn-sm" id="new-restaurant-button">Create Restaurant</button>
        </form>
    </div>
{% endblock %}

templates/restaurant/restaurant.html
{%  extends "base.html" %}
{%  block content %}
    <div class="container">
        <div class="col-sm">
            <h2 class="mb-3">{{restaurant.name}}</h2>
            <a class="btn btn-outline-success btn-sm mb-3" href="{{url_for('restaurant.create_restaurant_dish', restaurant_id=restaurant.id)}}">Add a Dish</a>
            <ul class="list-group">
                {% if restaurant.dishes|length > 0 %}
                    <h4>Dish List:</h4>
                    {% for dish in restaurant.dishes %}
                        <div class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                            <h4> {{dish.name}}</h4>
                            <small class="badge badge-info badge-pill"> {{ dish.review }} stars</small>
                        </div>
                        <a class="btn btn-danger btn-sm" href="{{ url_for('dish.delete_dish', dish_id=dish.id) }}">
                            Delete Dish
                        </a>
                    {% endfor %}
                {% else %}
                    <h4>There are no dishes yet!</h4>
                {% endif %}
            </ul>
        </div>
    </div>
{% endblock %}