controllers/restaurants_blueprint.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from resources.restaurant import Restaurant, RestaurantList, RestaurantListByUser, RestaurantByID, RestaurantGetRandom,\
    RestaurantByUser
from resources.dish import DishByRestaurantID, DishListByRestaurantID
from common.decorators import requires_login, requires_admin

restaurants_blueprint = Blueprint('restaurants', __name__)
restaurant_blueprint = Blueprint('restaurant', __name__)

# RESTAURANTS ################


@restaurants_blueprint.route('/', methods=['GET'])
@requires_login
def restaurant_list():
    user = session.get('user_name')
    payload, status_code = RestaurantListByUser.get(user)
    if status_code == 200:
        return render_template('restaurant/index.html', restaurants=payload['restaurants'],
                               user_name=session['user_name'], restaurant=Restaurant)
    else:
        return render_template('error.html', error='Please Login.')

# RESTAURANT ################


@restaurant_blueprint.route('/random', methods=['GET'])
@requires_login
# @requires_admin
def get_random():
    payload, status_code = RestaurantGetRandom.get()
    if status_code == 200:
        return redirect(url_for(".restaurant_by_name", name=payload['name']))
    else:
        return render_template('error.html', error=payload['message'])


@restaurant_blueprint.route('/<string:name>', methods=['GET'])
@requires_login
def restaurant_by_name(name):
    if session.get('user_name'):
        payload, status_code = Restaurant.get(name)
        payload.update(DishListByRestaurantID.get(payload['id'])[0])
        if status_code == 200:
            return render_template('restaurant/restaurant.html', restaurant=payload)
        else:
            return render_template('error.html', error=payload['message'])
    else:
        return render_template('error.html', error='Please Login.')


@restaurant_blueprint.route('/new', methods=['POST', 'GET'])
@requires_login
def create_restaurant():
    if request.method == 'GET':
        return render_template('restaurant/new.html')
    else:
        payload, status_code = Restaurant.post(request.form['name'])
        if status_code == 201:
            return redirect(url_for("restaurants.restaurant_list"))
        else:
            return render_template('error.html', error=payload['message'])


@restaurant_blueprint.route('/edit/<string:restaurant_id>', methods=['POST', 'GET'])
@requires_login
def edit_restaurant(restaurant_id):
    payload, status_code = RestaurantByID.get(restaurant_id)
    if request.method == 'POST':
        Restaurant.put(payload['name'])
        return redirect(url_for("restaurants.restaurant_list"))
    else:
        return render_template("restaurant/edit.html", restaurant=payload)


@restaurant_blueprint.route('/remove/<string:restaurant_id>', methods=['GET'])
@requires_login
def remove_restaurant_from_list(restaurant_id):
    payload, status_code = RestaurantByUser.delete(session.get('user_name'), restaurant_id)
    if status_code == 200:
        return redirect(url_for("restaurants.restaurant_list"))
    else:
        return render_template('error.html', error=payload['message'])


@restaurant_blueprint.route('/delete/<string:restaurant_id>', methods=['GET'])
@requires_login
@requires_admin
def delete_restaurant(restaurant_id):
    restaurant, status_code_fetch = RestaurantByID.get(restaurant_id)
    payload, status_code = Restaurant.delete(restaurant['name'])
    if status_code == 200:
        return redirect(url_for("restaurants.restaurant_list"))
    else:
        return render_template('error.html', error=payload['message'])


@restaurant_blueprint.route('/<string:restaurant_id>/dish/new', methods=['POST', 'GET'])
@requires_login
def create_restaurant_dish(restaurant_id):
    if request.method == 'GET':
        return render_template('restaurant/dish/new.html', restaurant_id=restaurant_id)
    else:
        DishByRestaurantID.post(restaurant_id)
        payload, status_code = RestaurantByID.get(restaurant_id)
        return redirect(url_for(".restaurant_by_name", name=payload['name']))

controllers/user_auth_blueprint.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from resources.user import UserLogin, UserRegister

user_login_blueprint = Blueprint('login', __name__)
user_register_blueprint = Blueprint('register', __name__)
user_profile_blueprint = Blueprint('profile', __name__)


@user_login_blueprint.route('', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('login.html')
    elif request.method == 'POST':
        user_name = request.form['user_name']
        password = request.form['password']
        payload, status_code = UserLogin.authenticate(user_name, password)
        if status_code == 200:
            UserLogin.login(user_name)
            return redirect(url_for('profile.profile', user_name=user_name))
        else:
            UserLogin.logout()
            return render_template('error.html', error=payload.get('msg'))


@user_register_blueprint.route('', methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template('register.html')
    elif request.method == 'POST':
        user_name = request.form['user_name']
        payload, status_code = UserRegister.post()
        if status_code == 201:
            UserLogin.login(user_name)
            return redirect(url_for('profile.profile', user_name=user_name))
        else:
            UserLogin.logout()
            return render_template('error.html', error=payload.get('msg'))


@user_profile_blueprint.route('/<string:user_name>', methods=['GET'])
def profile(user_name):
    if session.get('user_name') == user_name:
        return render_template('profile.html', username=session['user_name'])
    else:
        return render_template('error.html', error='Profile Not Found. Please login.')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Austin Eats</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css')}}">
</head>
<body>
<div class='content container mt-2'>
    <nav class="navbar navbar-expand-lg navbar-dark mb-3" style="background-color: #4f7a8c;">
        <a class="navbar-brand" href="/">Austin Eats</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('restaurants.restaurant_list') }}">My Restaurants</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('restaurant.get_random') }}">Restaurant Roulette</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('login.login') }}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('register.register') }}">Register</a>
                </li>
            </ul>
        </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert-{{ category }}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    <div class="mt-3">
    {% block content %}

    {%  endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</div>
</body>
</html>

templates/error.html
{%  extends "base.html" %}
{%  block content %}
    <form id="login-form">
        <h1> Error: {{ error }}</h1>
    </form>
{% endblock %}

templates/home.html
{%  extends "base.html" %}
{%  block content %}
    <h1> Welcome to Austin Eats!</h1>
    <a class="btn btn-outline-secondary btn-sm" href="/login"> Login</a>
    <a class="btn btn-outline-secondary btn-sm" href="/register"> Register a new User</a>
    <a class="btn btn-outline-secondary btn-sm" href="/restaurants"> See list of Restaurants</a>
{% endblock %}

templates/login.html
{%  extends "base.html" %}
{%  block content %}
    <div class="container auth-page-form" id="login-page-form">
        <h5>Login User:</h5>
        <form id="login-form" action="{{url_for('login.login')}}" method="POST">
            <div class="form-group">
                <label for="user_name">User Name</label>
                <input type="text" class='form-control' id="user_name" name="user_name" placeholder="John Doe">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class='form-control' id="password" name="password">
            </div>
            <div class="row">
                <div class="col-2">
                    <button type="submit" class="btn btn-outline-success btn-sm" id="login-button">Login</button>
                </div>
                <div class="col-10">
                    <a class="btn btn-outline-secondary btn-sm" href="/register"> Register a New User</a>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

templates/new_restaurant.html
{%  extends "base.html" %}
{%  block content %}
    <div class="container auth-page-form" id="new-restaurant-page-form">
        <h5>Create new Restaurant:</h5>
        <form id="new-restaurant" action="/restaurant/new" method="POST">
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class='form-control' id="restaurant_name" name="name">
            </div>
            <div class="form-group">
                <label for="review">Review</label>
                <input type="text" class='form-control' id="restaurant_review" name="review">
            </div>
            <button type="submit" class="btn btn-outline-success btn-sm" id="new-restaurant-button">Create Restaurant</button>
        </form>
    </div>
{% endblock %}

templates/new_restaurant_dish.html
{%  extends "base.html" %}
{%  block content %}
    <div class="container auth-page-form" id="new-restaurant-dish-page-form">
        <h5>Create new Dish:</h5>
        <form id="new-restaurant" action="/restaurant/{{restaurant_id}}/dish/new" method="POST">
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class='form-control' id="dish_name" name="name">
            </div>
            <div class="form-group">
                <label for="review">Review</label>
                <input type="text" class='form-control' id="dish_review" name="review">
            </div>
            <button type="submit" class="btn btn-outline-success btn-sm" id="new-dish-button">Create Dish</button>
        </form>
    </div>
{% endblock %}

templates/profile.html
{%  extends "base.html" %}
{%  block content %}
    <form id="login-form">
        <h1> Hello {{ username }}!</h1>
    </form>
    <a class="btn btn-outline-secondary btn-sm" href="/restaurants"> See list of Restaurants</a>
    <a class="btn btn-outline-secondary btn-sm" href="{{ url_for('restaurant.get_random') }}"> Choose a Random Restaurant</a>
{% endblock %}

templates/register.html
{%  extends "base.html" %}
{%  block content %}
    <div class="container auth-page-form" id="register-page-form">
        <h5>Register User:</h5>
        <form id="register-form" action="{{url_for('register.register')}}" method="POST">
            <div class="form-group">
                <label for="user_name">User Name</label>
                <input type="text" class='form-control' id="user_name" name="user_name">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class='form-control' id="password" name="password">
            </div>
            <button type="submit" class="btn btn-outline-secondary btn-sm" id="register-button">Register</button>
        </form>
    </div>
{% endblock %}